spring:
  datasource:
    url: jdbc:mysql://localhost:3306/volunteer?useSSL=false&serverTimezone=UTC
    username: root      # 替换为你的数据库用户名
    password: root      # 替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: VolunteerManagement
logging:
  level:
    root: INFO  # 设置根日志级别
    com.example.demo: DEBUG  # 设置特定包的日志级别
server:
  port: 8080  # 指定应用程序运行的端口
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定 MyBatis XML Mapper 文件位置
  type-aliases-package: com.example.domain  # 指定实体类包
